In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf


In [ ]:
from google.colab import files
uploaded = files.upload()


Saving Churn_Modelling.csv to Churn_Modelling (1).csv


In [ ]:
import io
dataset = pd.read_csv(io.BytesIO(uploaded['Churn_Modelling.csv']))

In [ ]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y) 

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)


[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [ ]:
# Female = 0
# Male = 1

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X) 

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [ ]:
# France = 1 0 0 
# Spain = 0 0 1
# Germany = 0 1 0
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0) 

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
ann = tf.keras.models.Sequential() 
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) 

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) 

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) 

In [ ]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy']) 

In [ ]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 2ms/step - loss: 0.6131 - accuracy: 0.7080
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4682 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4369 - accuracy: 0.7961
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4215 - accuracy: 0.8051
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4103 - accuracy: 0.8152
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3989 - accuracy: 0.8216
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3873 - accuracy: 0.8299
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3771 - accuracy: 0.8370
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3705 - accuracy: 0.8382
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3659 - accura

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1513   82]
 [ 198  207]]


0.86

In [ ]:
# Assignment - 4

X_customer = np.array([[1,0,0,600,1,40,3,60000,2,1,1,50000]])
y_customer = ann.predict(X_customer)
y_customer = (y_customer > 0.5)
print(y_customer)

1/1 [==============================] - 0s 73ms/step
[[ True]]


In [ ]:
# Yes the customer will be Exited